export const FETCH_FILMS_REQUEST = "FETCH_FILMS_REQUEST"
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS"
export const FETCH_FILMS_FAILED = "FETCH_FILMS_FAILED"
export const UPDATE_FILM = "UPDATE_FILM"